arb-dir: assets/translations
template-arb-file: en.arb
output-class: AppLocalizations
output-localization-file: app_localizations.dart
untranslated-messages-file: untranslated.txt
synthetic-package: true
