# Copyright (c) 2025 Shopping Bill App Project
# SPDX-License-Identifier: MIT
name: shopping_bill_app

packages:
  - .

scripts:
  lint: flutter analyze --fatal-infos --fatal-warnings
  format: flutter format .
