# Copyright (c) 2025 Shopping Bill App Project
# SPDX-License-Identifier: MIT
name: pix_pricer

description: Localization scaffolding.

publish_to: 'none'

version: 0.1.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
