# Copyright (c) 2025 Shopping Bill App Project
# SPDX-License-Identifier: MIT
name: pix_pricer

description: >-
  PixPricer Flutter scaffold featuring Riverpod state management and Drift-based
  persistence.

publish_to: "none"

version: 0.1.0-dev

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_secure_storage: any
  riverpod: any
  flutter_riverpod: any
  drift: any
  sqlite3_flutter_libs: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  riverpod_generator: any
  build_runner: any
  drift_dev: any
  accessibility_test: any
  pedantic: ^1.11.1
  riverpod_lint: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
