# Copyright (c) 2025 Shopping Bill App Project
# SPDX-License-Identifier: MIT
name: Build

on:
  push:
    branches: [main, beta, alpha]
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        platform: [android, ios]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Cache Flutter SDK
        uses: actions/cache@v3
        with:
          path: ~/flutter
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
          cache: true

      - name: Cache pub packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Bootstrap
        run: ./scripts/bootstrap.sh

      - name: Check Flutter project
        id: project-check
        run: |
          if [ -f pubspec.yaml ]; then
            echo "exists=true" >> "$GITHUB_OUTPUT"
          else
            echo "exists=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Run Tests
        if: steps.project-check.outputs.exists == 'true'
        run: flutter test --coverage

      - name: Build Android
        if: steps.project-check.outputs.exists == 'true' && matrix.platform == 'android'
        run: flutter build apk --debug

      - name: MobSF Scan Android
        if: steps.project-check.outputs.exists == 'true' && matrix.platform == 'android'
        uses: MobSF/mobsf-action@v1
        with:
          artifact_path: build/app/outputs/flutter-apk/app-debug.apk
          platform: android

      - name: Build iOS
        if: steps.project-check.outputs.exists == 'true' && matrix.platform == 'ios'
        run: flutter build ios --no-codesign

      - name: MobSF Scan iOS
        if: steps.project-check.outputs.exists == 'true' && matrix.platform == 'ios'
        uses: MobSF/mobsf-action@v1
        with:
          artifact_path: build/ios/iphoneos/Runner.app
          platform: ios

      - name: Upload artifacts
        if: steps.project-check.outputs.exists == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: app-${{ matrix.platform }}
          path: build
          if-no-files-found: error
