name: Deploy Beta

on:
  push:
    tags:
      - 'v*.*.*-beta*'

jobs:
  deploy:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: maierj/fastlane-action@v2.2.0
        with:
          lane: beta
        env:
          APPSTORE_CONNECT_API_KEY: ${{ secrets.APPSTORE_CONNECT_API_KEY }}
          PLAY_KEY_JSON: ${{ secrets.PLAY_KEY_JSON }}
