name: Docs

on:
  # Publish docs whenever commits land on main
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: python -m pip install --upgrade pip
      - run: pip install -r docs/requirements.txt
      # Build documentation and fail on warnings
      - run: sphinx-build -b html -W --keep-going docs docs/_build/html
      - uses: actions/upload-pages-artifact@v1
        with:
          path: docs/_build/html
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v1
